# Generated by Django 5.1.5 on 2025-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
