# Generated by Django 5.1.5 on 2025-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0004_taskclass_task_task_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
